<?php
function luvumbo_latest_job_offers_block_info() {
    $blocks = array();

    $blocks['latest_3_job_offers'] = array(
        'info' => t('Latest job offers'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );

    return $blocks;
}


function luvumbo_latest_job_offers_block_view($delta = '') {
    switch ($delta) {
        case 'latest_3_job_offers':
            $block['subject'] = t('Latest job offers');
            $block['content'] = luvumbo_latest_job_offers_block_content();//MYMODULE_BLOCK_FUNCTION_ITEMS(); //_get_latest_job_offers_tpl();
            break;
    }

    return $block;
}

function luvumbo_latest_job_offers_block_content(){

    $query = new EntityFieldQuery();
    $entities = $query->entityCondition('entity_type', 'node')
        ->propertyCondition('type', 'job_offer')
        ->propertyOrderBy('created', 'DESC')
        ->range(0, 3)
        ->execute();


    if (!empty($entities['node'])) {
        $three_nodes = node_load_multiple(array_keys($entities['node']));
    }

    $items = array();
    foreach($three_nodes as $key => $value) {
        $items[$key] = $value;
    }
    return theme('luvumbo_latest_job_offers_block_content', array('items' => $items));
}

//here you are registering your default tpl for the above block
function luvumbo_latest_job_offers_theme() {
    $module_path = drupal_get_path('module', 'luvumbo_latest_job_offers');
    $base = array(
        'path' => "$module_path/theme",
    );
    return array(
        'luvumbo_latest_job_offers_block_content' => $base + array(
                'template' => 'luvumbo_latest_job_offers_block',  //leave off .tpl.php
                'variables' => array('items' => NULL,),
            ),
    );
}
