<?php
function luvumbo_contact_block_info() {
    $blocks = array();

    $blocks['contact_form'] = array(
        'info' => t('Contact Form'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );

    return $blocks;
}


function luvumbo_contact_block_view($delta = '') {
    switch ($delta) {
        case 'contact_form':
            $block['subject'] = t('Contact Us');
            $block['content'] = drupal_get_form('luvumbo_contact_contact_form');
            break;
    }

    return $block;
}

function luvumbo_contact_contact_form($form, &$form_state) {

    $form['luvumbo_contact_name'] = array(
        '#type' => 'textfield',
        '#attributes' => array(
            'placeholder' => t('Votre nom'),
            'class'       => array('form-control', 'bg-light', 'border-0'),
        ),
        '#required' => TRUE,
    );

    $form['luvumbo_contact_email'] = array(
        '#type' => 'textfield',
        '#attributes' => array(
            'placeholder' => t('Votre email'),
            'class'       => array('form-control', 'bg-light', 'border-0'),
        ),
        '#required' => TRUE,
    );

    $form['luvumbo_contact_subject'] = array(
        '#type' => 'select',
        '#options' => array(
            t("Select a subject")      => t("Selectionnez le sujet"),
            t("Candidature")           => t("Candidature"),
            t("Client")                => t("Client"),
            t("Demande d'information") => t("Demande d'information"),
            t("Coopération")           => t("Coopération"),
            t("Support technique")     => t("Support technique"),
        ),
        '#attributes' => array(
            'class'       => array('form-select', 'bg-light', 'border-0'),
        ),
        '#default_value' => array(0),
        '#required' => TRUE,
    );

    $form['luvumbo_contact_message'] = array(
        '#type'       => 'textarea',
        '#title'      => t('Message'),
        '#attributes' => array(
            'placeholder' => t('Message'),
            'class'       => array('form-control', 'bg-light', 'border-0'),
        ),
        '#required'   => TRUE,
    );

    $form['luvumbo_contact_submit'] = array(
        '#type' => 'submit',
        '#attributes' => array(
            'class'       => array('btn', ' btn-dark', ' w-100', ' py-3'),
        ),
        '#value' => t('Envoyez Email'),
    );


    return $form;
}

function luvumbo_contact_contact_form_submit($form, &$form_state) {
    $values = $form_state['values'];

    $to = 'contact@ai-lconseil.fr';
    $from = $values['luvumbo_contact_email'];
    $subject = $values['luvumbo_contact_subject'];
    $message = $values['luvumbo_contact_message'];

    drupal_mail('luvumbo_contact', 'contact_form', $to, language_default(), array(
        'name' => $values['luvumbo_contact_name'],
        'email' => $values['luvumbo_contact_email'],
        'subject' => $values['luvumbo_contact_subject'],
        'message' => $values['luvumbo_contact_message'],
    ), $from);

    drupal_set_message(t('Your message has been sent.'));
}


function luvumbo_contact_mail($key, &$message, $params) {
    switch ($key) {
        case 'contact_form':
            $message['subject'] = t('New contact form submission: @subject', array('@subject' => $params['subject']));
            $message['body'][] = t('Name: @name', array('@name' => $params['name']));
            $message['body'][] = t('Email: @email', array('@email' => $params['email']));
            $message['body'][] = t('Message: @message', array('@message' => $params['message']));
            break;
    }
}


